feat: added strategy with ape template
bufander/yearnv3-ape-aave-lender pull request #1
Opened 2022-09-13 17:07 UTC by bufander

2022-09-15 14:12 UTC, jmonteer requested changes
This strategy is liquid so it should be able to call `_freeFunds` from `withdraw`, that needs to be overriden to include it (so that the vault doesn't need anyone else freeing funds in advance).

Probably the same with _invest and deposit

2022-09-15 16:03 UTC, bufander commented on tests/conftest.py
> +# TODO: deploying vault, as there is no vault yet on mainnet. To be deleted once vault v3 is deployed
fair enough, although we need to figure out a better way of importing the VaultV3 code, as copy/pasting it on the repo is not good enough

2022-09-16 14:39 UTC, bufander commented
@jmonteer I've re-written the strategy in a simpler way, just using minimum api vault needs. Please give it a look

2022-09-21 16:33 UTC, jmonteer reviewed
I would use this work to separate between BaseStrategy.sol (implementing all external functions) and Strategy.sol that inherits from it but implements only functions that are coing to be unique for 1 strategy

2022-09-22 10:27 UTC, bufander commented on contracts/Strategy.sol
> +        // transfer and invest
Done

2022-09-22 10:33 UTC, bufander commented on contracts/Strategy.sol
> +    }
Done

2022-09-22 10:34 UTC, bufander commented on contracts/Strategy.sol
> +                            IERC20(asset).balanceOf(aToken)
Good catch!

2022-09-22 10:48 UTC, bufander commented on contracts/Strategy.sol
> +    mapping(address => uint256) private balances;
done

2022-09-22 11:02 UTC, bufander commented on contracts/Strategy.sol
> +    function deposit(uint256 assets, address receiver)
Moved

2022-09-22 11:02 UTC, bufander commented on contracts/Strategy.sol
> +    function _withdraw(
Moved

2022-09-22 11:02 UTC, bufander commented on contracts/Strategy.sol
> +    function _convert_to_shares(uint256 assets) public view returns (uint256) {
Moved

2022-09-22 11:02 UTC, bufander commented on contracts/Strategy.sol
> +    function _convert_to_assets(uint256 shares) public view returns (uint256) {
Moved

2022-09-22 11:02 UTC, bufander commented on contracts/Strategy.sol
> +    function totalAssets() public view returns (uint256) {
Moved

2022-09-22 11:04 UTC, bufander commented
@jmonteer  
Following your comments I've created the BaseStrategy. If it fits you I can update ape strategy mix with this new BaseStrategy

2022-09-27 10:04 UTC, jmonteer requested changes
last changes

2022-09-27 12:24 UTC, bufander commented on contracts/BaseStrategy.sol
> +        return _withdraw(amount, receiver, owner);
Moved there

2022-09-27 12:24 UTC, bufander commented on contracts/BaseStrategy.sol
> +    function _withdraw(
I've taken all code from the method

2022-09-27 12:24 UTC, bufander commented on contracts/Strategy.sol
> +        IERC20(asset).transfer(receiver, amount_to_withdraw);
Done!

2022-09-27 12:24 UTC, bufander commented on contracts/BaseStrategy.sol
> +        return _totalAssets();
Ok, I implemented it that way so it´s more clear

2022-11-06 21:28 UTC, merged